heat_template_version: 2015-04-30

description: >
  Returns the control plane port (provisioning network) as the ip_address.

parameters:
  ControlPlaneIP:
    description: IP address on the control plane
    type: string
  ControlPlaneNetwork:
    description: Name of the control plane network
    default: ctlplane
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  NetworkName:
    description: # Here for compatability with vip.yaml
    default: ''
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string

outputs:
  ip_address:
    description: pass thru network IP
    value: {get_param: ControlPlaneIP}
  ip_subnet:
    description: IP/Subnet CIDR for the pass thru network IP
    value:
          list_join:
            - ''
            - - {get_param: ControlPlaneIP}
              - '/'
              - {get_param: ControlPlaneSubnetCidr}
