resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameters:
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  Controller-1::NeutronExternalNetworkBridge: "''"
  #
  Compute-1::NeutronBridgeMappings: datacentre:br-ex,br-eth1:br-eth1
  Compute-1::NeutronFlatNetworks: datacentre,br-eth1
  Compute-1::NeutronNetworkType: vxlan
  Compute-1::NeutronNetworkVLANRanges: datacentre:1:1000,br-eth1:108:108
  Compute-1::NeutronTunnelTypes: vxlan
  Controller-1::NeutronBridgeMappings: datacentre:br-ex,br-eth1:br-eth1
  Controller-1::NeutronFlatNetworks: datacentre,br-eth1
  Controller-1::NeutronNetworkType: vxlan
  Controller-1::NeutronNetworkVLANRanges: datacentre:1:1000,br-eth1:108:108
  Controller-1::NeutronTunnelTypes: vxlan

parameter_defaults:
  ExternalAllocationPools: [{'start': '172.31.0.18', 'end': '172.31.0.50'}]
  ExternalInterfaceDefaultRoute: 172.31.0.1
  ExternalNetCidr: 172.31.0.0/24
  ExternalNetworkVlanID: 100
  InternalApiAllocationPools: [{'start': '172.31.1.18', 'end': '172.31.1.254'}]
  InternalApiNetCidr: 172.31.1.0/24
  InternalApiNetworkVlanID: 101
  StorageAllocationPools: [{'start': '172.31.2.18', 'end': '172.31.2.254'}]
  StorageNetCidr: 172.31.2.0/24
  StorageNetworkVlanID: 104
  StorageMgmtAllocationPools: [{'start': '172.31.3.18', 'end': '172.31.3.254'}]
  StorageMgmtNetCidr: 172.31.3.0/24
  StorageMgmtNetworkVlanID: 105
  TenantAllocationPools: [{'start': '172.22.208.18', 'end': '172.22.208.254'}]
  TenantNetCidr: 172.22.208.0/20
  TenantNetworkVlanID: 103
  # Customize bonding options if required (will be ignored if bonds are not used)
  # BondInterfaceOvsOptions:
  #     "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
