parameters:
  BlockStorageHostnameFormat: '%stackname%-blockstorage-%index%'
  Ceph-Storage-1::EnablePackageInstall: 'false'
  Ceph-Storage-1::Flavor: baremetal
  Ceph-Storage-1::Image: overcloud-full
  Ceph-Storage-1::ImageUpdatePolicy: REBUILD_PRESERVE_EPHEMERAL
  Ceph-Storage-1::KeyName: default
  Ceph-Storage-1::NtpServer: ''
  Ceph-Storage-1::ServiceNetMap:
    BlockStorageHostnameResolveNetwork: internal_api
    CeilometerApiNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephStorageHostnameResolveNetwork: storage
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    ComputeHostnameResolveNetwork: internal_api
    ControllerHostnameResolveNetwork: internal_api
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    HeatApiNetwork: internal_api
    HorizonNetwork: internal_api
    KeystoneAdminApiNetwork: internal_api
    KeystonePublicApiNetwork: internal_api
    MemcachedNetwork: internal_api
    MongoDbNetwork: internal_api
    MysqlNetwork: internal_api
    NeutronApiNetwork: internal_api
    NeutronTenantNetwork: tenant
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt
    SwiftProxyNetwork: storage
  Ceph-Storage-1::UpdateIdentifier: ''
  Ceph-Storage-1::count: '0'
  Ceph-Storage-1::removal_policies: []
  CephAdminKey: ''
  CephClusterFSID: ''
  CephMonKey: ''
  CephStorageHostnameFormat: '%stackname%-cephstorage-%index%'
  Cinder-Storage-1::CinderEnableIscsiBackend: true
  Cinder-Storage-1::CinderISCSIHelper: lioadm
  Cinder-Storage-1::CinderLVMLoopDeviceSize: 5000
  Cinder-Storage-1::CinderPassword: unset
  Cinder-Storage-1::Debug: ''
  Cinder-Storage-1::EnablePackageInstall: 'false'
  Cinder-Storage-1::ExtraConfig: {}
  Cinder-Storage-1::Flavor: baremetal
  Cinder-Storage-1::GlancePort: '9292'
  Cinder-Storage-1::GlanceProtocol: http
  Cinder-Storage-1::Image: overcloud-full
  Cinder-Storage-1::KeyName: default
  Cinder-Storage-1::NtpServer: ''
  Cinder-Storage-1::RabbitClientPort: 5672
  Cinder-Storage-1::RabbitClientUseSSL: false
  Cinder-Storage-1::RabbitPassword: guest
  Cinder-Storage-1::RabbitUserName: guest
  Cinder-Storage-1::ServiceNetMap:
    BlockStorageHostnameResolveNetwork: internal_api
    CeilometerApiNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephStorageHostnameResolveNetwork: storage
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    ComputeHostnameResolveNetwork: internal_api
    ControllerHostnameResolveNetwork: internal_api
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    HeatApiNetwork: internal_api
    HorizonNetwork: internal_api
    KeystoneAdminApiNetwork: internal_api
    KeystonePublicApiNetwork: internal_api
    MemcachedNetwork: internal_api
    MongoDbNetwork: internal_api
    MysqlNetwork: internal_api
    NeutronApiNetwork: internal_api
    NeutronTenantNetwork: tenant
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt
    SwiftProxyNetwork: storage
  Cinder-Storage-1::SnmpdReadonlyUserName: ro_snmp_user
  Cinder-Storage-1::SnmpdReadonlyUserPassword: unset
  Cinder-Storage-1::UpdateIdentifier: ''
  Cinder-Storage-1::count: '0'
  Cinder-Storage-1::removal_policies: []
  Compute-1::AdminPassword: unset
  Compute-1::CeilometerComputeAgent: ''
  Compute-1::CeilometerMeteringSecret: unset
  Compute-1::CeilometerPassword: unset
  Compute-1::CinderEnableNfsBackend: false
  Compute-1::Debug: ''
  Compute-1::EnablePackageInstall: 'false'
  Compute-1::ExtraConfig: {}
  Compute-1::Flavor: baremetal
  Compute-1::GlancePort: '9292'
  Compute-1::GlanceProtocol: http
  Compute-1::Image: overcloud-full
  Compute-1::ImageUpdatePolicy: REBUILD_PRESERVE_EPHEMERAL
  Compute-1::KeyName: default
  Compute-1::NeutronAgentMode: dvr_snat
  Compute-1::NeutronAllowL3AgentFailover: 'True'
  Compute-1::NeutronBridgeMappings: datacentre:br-ex
  Compute-1::NeutronDVR: 'False'
  Compute-1::NeutronEnableTunnelling: 'True'
  Compute-1::NeutronFlatNetworks: datacentre
  Compute-1::NeutronL3HA: 'False'
  Compute-1::NeutronMechanismDrivers: openvswitch
  Compute-1::NeutronMetadataProxySharedSecret: unset
  Compute-1::NeutronNetworkType: gre
  Compute-1::NeutronNetworkVLANRanges: datacentre:1:1000
  Compute-1::NeutronPassword: unset
  Compute-1::NeutronPhysicalBridge: br-ex
  Compute-1::NeutronPublicInterface: nic1
  Compute-1::NeutronPublicInterfaceRawDevice: ''
  Compute-1::NeutronTunnelIdRanges: 1:1000
  Compute-1::NeutronTunnelTypes: gre
  Compute-1::NeutronVniRanges: 1:1000
  Compute-1::NovaComputeDriver: libvirt.LibvirtDriver
  Compute-1::NovaComputeExtraConfig: {}
  Compute-1::NovaComputeLibvirtType: qemu
  Compute-1::NovaEnableRbdBackend: false
  Compute-1::NovaPassword: unset
  Compute-1::NtpServer: ''
  Compute-1::RabbitClientPort: 5672
  Compute-1::RabbitClientUseSSL: false
  Compute-1::RabbitPassword: guest
  Compute-1::RabbitUserName: guest
  Compute-1::ServiceNetMap:
    BlockStorageHostnameResolveNetwork: internal_api
    CeilometerApiNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephStorageHostnameResolveNetwork: storage
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    ComputeHostnameResolveNetwork: internal_api
    ControllerHostnameResolveNetwork: internal_api
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    HeatApiNetwork: internal_api
    HorizonNetwork: internal_api
    KeystoneAdminApiNetwork: internal_api
    KeystonePublicApiNetwork: internal_api
    MemcachedNetwork: internal_api
    MongoDbNetwork: internal_api
    MysqlNetwork: internal_api
    NeutronApiNetwork: internal_api
    NeutronTenantNetwork: tenant
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt
    SwiftProxyNetwork: storage
  Compute-1::SnmpdReadonlyUserName: ro_snmp_user
  Compute-1::SnmpdReadonlyUserPassword: unset
  Compute-1::UpdateIdentifier: ''
  Compute-1::count: '1'
  Compute-1::removal_policies: []
  ComputeHostnameFormat: '%stackname%-compute-%index%'
  ControlFixedIPs: []
  Controller-1::AdminPassword: unset
  Controller-1::AdminToken: unset
  Controller-1::CeilometerBackend: mongodb
  Controller-1::CeilometerMeteringSecret: unset
  Controller-1::CeilometerPassword: unset
  Controller-1::CinderBackendConfig: {}
  Controller-1::CinderEnableIscsiBackend: true
  Controller-1::CinderEnableNfsBackend: false
  Controller-1::CinderEnableRbdBackend: false
  Controller-1::CinderISCSIHelper: lioadm
  Controller-1::CinderLVMLoopDeviceSize: 5000
  Controller-1::CinderNfsMountOptions: ''
  Controller-1::CinderNfsServers: ''
  Controller-1::CinderPassword: unset
  Controller-1::CloudName: overcloud
  Controller-1::ControlVirtualInterface: br-ex
  Controller-1::ControllerExtraConfig: {}
  Controller-1::Debug: ''
  Controller-1::EnableCephStorage: false
  Controller-1::EnableGalera: true
  Controller-1::EnablePacemaker: false
  Controller-1::EnablePackageInstall: 'false'
  Controller-1::EnableSwiftStorage: true
  Controller-1::ExtraConfig: {}
  Controller-1::Flavor: baremetal
  Controller-1::GlanceBackend: swift
  Controller-1::GlanceFilePcmkDevice: ''
  Controller-1::GlanceFilePcmkFstype: nfs
  Controller-1::GlanceFilePcmkManage: false
  Controller-1::GlanceFilePcmkOptions: ''
  Controller-1::GlanceLogFile: ''
  Controller-1::GlanceNotifierStrategy: noop
  Controller-1::GlancePassword: unset
  Controller-1::GlancePort: '9292'
  Controller-1::GlanceProtocol: http
  Controller-1::HeatPassword: unset
  Controller-1::HeatStackDomainAdminPassword: unset
  Controller-1::Image: overcloud-full
  Controller-1::ImageUpdatePolicy: REBUILD_PRESERVE_EPHEMERAL
  Controller-1::KeyName: default
  Controller-1::KeystoneCACertificate: ''
  Controller-1::KeystoneSSLCertificate: ''
  Controller-1::KeystoneSSLCertificateKey: ''
  Controller-1::KeystoneSigningCertificate: ''
  Controller-1::KeystoneSigningKey: ''
  Controller-1::MysqlInnodbBufferPoolSize: 0
  Controller-1::MysqlMaxConnections: 1024
  Controller-1::NeutronAgentMode: dvr_snat
  Controller-1::NeutronAllowL3AgentFailover: 'True'
  Controller-1::NeutronBridgeMappings: datacentre:br-ex
  Controller-1::NeutronDVR: 'False'
  Controller-1::NeutronDhcpAgentsPerNetwork: 3
  Controller-1::NeutronDnsmasqOptions: dhcp-option-force=26,1400
  Controller-1::NeutronEnableTunnelling: 'True'
  Controller-1::NeutronExternalNetworkBridge: br-ex
  Controller-1::NeutronFlatNetworks: datacentre
  Controller-1::NeutronL3HA: 'False'
  Controller-1::NeutronMechanismDrivers: openvswitch
  Controller-1::NeutronMetadataProxySharedSecret: unset
  Controller-1::NeutronNetworkType: gre
  Controller-1::NeutronNetworkVLANRanges: datacentre:1:1000
  Controller-1::NeutronPassword: unset
  Controller-1::NeutronPublicInterface: nic1
  Controller-1::NeutronPublicInterfaceDefaultRoute: ''
  Controller-1::NeutronPublicInterfaceIP: ''
  Controller-1::NeutronPublicInterfaceRawDevice: ''
  Controller-1::NeutronPublicInterfaceTag: ''
  Controller-1::NeutronTunnelIdRanges: 1:1000
  Controller-1::NeutronTunnelTypes: gre
  Controller-1::NeutronVniRanges: 1:1000
  Controller-1::NovaPassword: unset
  Controller-1::NtpServer: ''
  Controller-1::PublicVirtualInterface: br-ex
  Controller-1::RabbitClientPort: 5672
  Controller-1::RabbitClientUseSSL: false
  Controller-1::RabbitPassword: guest
  Controller-1::RabbitUserName: guest
  Controller-1::SSLCACertificate: ''
  Controller-1::SSLCertificate: ''
  Controller-1::SSLKey: ''
  Controller-1::ServiceNetMap: &id001
    BlockStorageHostnameResolveNetwork: internal_api
    CeilometerApiNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephStorageHostnameResolveNetwork: storage
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    ComputeHostnameResolveNetwork: internal_api
    ControllerHostnameResolveNetwork: internal_api
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    HeatApiNetwork: internal_api
    HorizonNetwork: internal_api
    KeystoneAdminApiNetwork: internal_api
    KeystonePublicApiNetwork: internal_api
    MemcachedNetwork: internal_api
    MongoDbNetwork: internal_api
    MysqlNetwork: internal_api
    NeutronApiNetwork: internal_api
    NeutronTenantNetwork: tenant
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt
    SwiftProxyNetwork: storage
  Controller-1::SnmpdReadonlyUserName: ro_snmp_user
  Controller-1::SnmpdReadonlyUserPassword: unset
  Controller-1::SwiftHashSuffix: unset
  Controller-1::SwiftMinPartHours: 1
  Controller-1::SwiftMountCheck: 'false'
  Controller-1::SwiftPartPower: 10
  Controller-1::SwiftPassword: unset
  Controller-1::SwiftReplicas: 3
  Controller-1::UpdateIdentifier: ''
  Controller-1::count: '1'
  Controller-1::removal_policies: []
  ControllerHostnameFormat: '%stackname%-controller-%index%'
  NeutronControlPlaneID: ''
  NeutronPublicInterfaceTag: ''
  NeutronTunnelIdRanges: 1:1000
  NeutronVniRanges: 1:1000
  ObjectStorageHostnameFormat: '%stackname%-objectstorage-%index%'
  PublicVirtualFixedIPs: []
  PublicVirtualNetwork: ctlplane
  RabbitCookieSalt: unset
  ServiceNetMap: *id001
  Swift-Storage-1::EnablePackageInstall: 'false'
  Swift-Storage-1::Flavor: baremetal
  Swift-Storage-1::HashSuffix: unset
  Swift-Storage-1::Image: overcloud-full
  Swift-Storage-1::KeyName: default
  Swift-Storage-1::MinPartHours: 1
  Swift-Storage-1::MountCheck: 'false'
  Swift-Storage-1::NtpServer: ''
  Swift-Storage-1::PartPower: 10
  Swift-Storage-1::Replicas: 3
  Swift-Storage-1::ServiceNetMap:
    BlockStorageHostnameResolveNetwork: internal_api
    CeilometerApiNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephStorageHostnameResolveNetwork: storage
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    ComputeHostnameResolveNetwork: internal_api
    ControllerHostnameResolveNetwork: internal_api
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    HeatApiNetwork: internal_api
    HorizonNetwork: internal_api
    KeystoneAdminApiNetwork: internal_api
    KeystonePublicApiNetwork: internal_api
    MemcachedNetwork: internal_api
    MongoDbNetwork: internal_api
    MysqlNetwork: internal_api
    NeutronApiNetwork: internal_api
    NeutronTenantNetwork: tenant
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt
    SwiftProxyNetwork: storage
  Swift-Storage-1::SnmpdReadonlyUserName: ro_snmp_user
  Swift-Storage-1::SnmpdReadonlyUserPassword: unset
  Swift-Storage-1::UpdateIdentifier: ''
  Swift-Storage-1::count: '0'
  Swift-Storage-1::removal_policies: []
resource_registry:
  OS::TripleO::AllNodes::SoftwareConfig: puppet/all-nodes-config.yaml
  OS::TripleO::BlockStorage: puppet/cinder-storage-puppet.yaml
  OS::TripleO::BlockStorage::Net::SoftwareConfig: net-config-noop.yaml
  OS::TripleO::BlockStorage::Ports::InternalApiPort: network/ports/noop.yaml
  OS::TripleO::BlockStorage::Ports::StorageMgmtPort: network/ports/noop.yaml
  OS::TripleO::BlockStorage::Ports::StoragePort: network/ports/noop.yaml
  OS::TripleO::BlockStoragePostDeployment: puppet/cinder-storage-post.yaml
  OS::TripleO::BootstrapNode::SoftwareConfig: puppet/bootstrap-config.yaml
  OS::TripleO::CephClusterConfig::SoftwareConfig: puppet/ceph-cluster-config.yaml
  OS::TripleO::CephStorage: puppet/ceph-storage-puppet.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: net-config-noop.yaml
  OS::TripleO::CephStorage::Ports::StorageMgmtPort: network/ports/noop.yaml
  OS::TripleO::CephStorage::Ports::StoragePort: network/ports/noop.yaml
  OS::TripleO::CephStoragePostDeployment: puppet/ceph-storage-post-puppet.yaml
  OS::TripleO::Compute: puppet/compute-puppet.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: net-config-noop.yaml
  OS::TripleO::Compute::Ports::InternalApiPort: network/ports/noop.yaml
  OS::TripleO::Compute::Ports::StoragePort: network/ports/noop.yaml
  OS::TripleO::Compute::Ports::TenantPort: network/ports/noop.yaml
  OS::TripleO::ComputePostDeployment: puppet/compute-post-puppet.yaml
  OS::TripleO::Controller: puppet/controller-puppet.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: net-config-bridge.yaml
  OS::TripleO::Controller::Ports::ExternalPort: network/ports/ctlplane_vip.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: network/ports/noop.yaml
  OS::TripleO::Controller::Ports::RedisVipPort: network/ports/ctlplane_vip.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: network/ports/noop.yaml
  OS::TripleO::Controller::Ports::StoragePort: network/ports/noop.yaml
  OS::TripleO::Controller::Ports::TenantPort: network/ports/noop.yaml
  OS::TripleO::ControllerConfig: puppet/controller-config-pacemaker.yaml
  OS::TripleO::ControllerExtraConfigPre: puppet/extraconfig/pre_deploy/default.yaml
  OS::TripleO::ControllerPostDeployment: puppet/controller-post-puppet.yaml
  OS::TripleO::Network: network/networks.yaml
  OS::TripleO::Network::External: network/noop.yaml
  OS::TripleO::Network::InternalApi: network/noop.yaml
  OS::TripleO::Network::Ports::NetIpListMap: network/ports/net_ip_list_map.yaml
  OS::TripleO::Network::Ports::NetIpMap: network/ports/net_ip_map.yaml
  OS::TripleO::Network::Storage: network/noop.yaml
  OS::TripleO::Network::StorageMgmt: network/noop.yaml
  OS::TripleO::Network::Tenant: network/noop.yaml
  OS::TripleO::NodeExtraConfigPost: extraconfig/post_deploy/default.yaml
  OS::TripleO::NodeUserData: firstboot/userdata_default.yaml
  OS::TripleO::ObjectStorage: puppet/swift-storage-puppet.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: net-config-noop.yaml
  OS::TripleO::ObjectStoragePostDeployment: puppet/swift-storage-post.yaml
  OS::TripleO::SoftwareDeployment: OS::Heat::StructuredDeployment
  OS::TripleO::SwiftDevicesAndProxy::SoftwareConfig: puppet/swift-devices-and-proxy-config.yaml
  OS::TripleO::SwiftStorage::Ports::InternalApiPort: network/ports/noop.yaml
  OS::TripleO::SwiftStorage::Ports::StorageMgmtPort: network/ports/noop.yaml
  OS::TripleO::SwiftStorage::Ports::StoragePort: network/ports/noop.yaml
  OS::TripleO::Tasks::PackageUpdate: extraconfig/tasks/yum_update.yaml
  OS::TripleO::VipConfig: puppet/vip-config.yaml
  Tuskar::Ceph-Storage-1: provider-Ceph-Storage-1.yaml
  Tuskar::Cinder-Storage-1: provider-Cinder-Storage-1.yaml
  Tuskar::Compute-1: provider-Compute-1.yaml
  Tuskar::Controller-1: provider-Controller-1.yaml
  Tuskar::Swift-Storage-1: provider-Swift-Storage-1.yaml
