#License
#=======
#  Copyright (c) 2015 Genome Research Ltd. 
#
#  Author: James Beal <James.Beal@sanger.ac.uk>, Dave Holland <dh3@sanger.ac.uk>
#
#  This file is part of  https://github.com/wtsi-ssg/openstack-config
#
#  This  is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.   This program is distributed
#  in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU General Public License for more details. 
#  You should have received a copy of the GNU General Public License along
#  with this program. If not, see <http://www.gnu.org/licenses/>. 
#

---
# controllers: edit haproxy.cfg then reload haproxy
- hosts: set2-controllers
  tasks:
  - name: keystone timeout
    replace: dest=/etc/keystone/keystone.conf regexp='^expiration = 3600$' replace='expiration = 28800'
    notify:
        - restart keystone
  - name: horizon timeout
    replace: dest=/usr/share/openstack-dashboard/openstack_dashboard/settings.py regexp='^SESSION_TIMEOUT = 1800$' replace='SESSION_TIMEOUT = 28800'
    notify:
        - restart horizon

  handlers:
  - name: restart keystone 
    service: name=openstack-keystone state=restarted
  - name: restart horizon
    service: name=httpd state=restarted
