resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameters:
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  Controller-1::NeutronExternalNetworkBridge: "br-ex"
  Compute-1::NeutronNetworkType: vxlan
  Compute-1::NeutronTunnelTypes: vxlan
  Controller-1::NeutronNetworkType: vxlan
  Controller-1::NeutronTunnelTypes: vxlan

parameter_defaults:
  ExternalAllocationPools: [{'start': '172.31.4.18', 'end': '172.31.4.50'}]
  ExternalInterfaceDefaultRoute: 172.31.4.1
  ExternalNetCidr: 172.31.4.0/24
  ExternalNetworkVlanID: 200
  InternalApiAllocationPools: [{'start': '172.31.5.18', 'end': '172.31.5.254'}]
  InternalApiNetCidr: 172.31.5.0/24
  InternalApiNetworkVlanID: 201
  StorageAllocationPools: [{'start': '172.31.6.18', 'end': '172.31.6.254'}]
  StorageNetCidr: 172.31.6.0/24
  StorageNetworkVlanID: 204
  StorageMgmtAllocationPools: [{'start': '172.31.7.18', 'end': '172.31.7.254'}]
  StorageMgmtNetCidr: 172.31.7.0/24
  StorageMgmtNetworkVlanID: 205
  TenantAllocationPools: [{'start': '172.22.240.18', 'end': '172.22.240.254'}]
  TenantNetCidr: 172.22.240.0/20
  TenantNetworkVlanID: 203
  # Customize bonding options if required (will be ignored if bonds are not used)
  # BondInterfaceOvsOptions:
  #     "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"

