description: OpenStack swift storage node configured by Puppet
heat_template_version: 2015-04-30
outputs:
  config_identifier:
    description: identifier which changes if the node configuration may need re-applying
    value:
      get_attr:
      - SwiftStorageHieraDeploy
      - deploy_stdout
  hosts_entry:
    value:
      str_replace:
        params:
          HOST:
            get_attr:
            - SwiftStorage
            - name
          IP:
            get_attr:
            - NetIpMap
            - net_ip_map
            - get_param:
              - ServiceNetMap
              - ObjectStorageHostnameResolveNetwork
        template: IP HOST.localdomain HOST
  internal_api_ip_address:
    description: IP address of the server in the internal_api network
    value:
      get_attr:
      - InternalApiPort
      - ip_address
  nova_server_resource:
    description: Heat resource handle for the swift storage server
    value:
      get_resource: SwiftStorage
  storage_ip_address:
    description: IP address of the server in the storage network
    value:
      get_attr:
      - StoragePort
      - ip_address
  storage_mgmt_ip_address:
    description: IP address of the server in the storage_mgmt network
    value:
      get_attr:
      - StorageMgmtPort
      - ip_address
  swift_device:
    description: Swift device formatted for swift-ring-builder
    value:
      str_replace:
        params:
          IP:
            get_attr:
            - NetIpMap
            - net_ip_map
            - get_param:
              - ServiceNetMap
              - SwiftMgmtNetwork
        template: r1z1-IP:%PORT%/d1
parameters:
  EnablePackageInstall:
    default: 'false'
    description: Set to true to enable package installation via Puppet
    type: boolean
  Flavor:
    constraints:
    - custom_constraint: nova.flavor
    description: Flavor for Swift storage nodes to request when deploying.
    type: string
  HashSuffix:
    default: unset
    description: A random string to be used as a salt when hashing to determine mappings
      in the ring.
    hidden: true
    type: string
  Hostname:
    default: ''
    type: string
  Image:
    default: overcloud-swift-storage
    type: string
  KeyName:
    default: default
    description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    type: string
  MinPartHours:
    default: 1
    description: The minimum time (in hours) before a partition in a ring can be moved
      following a rebalance.
    type: number
  MountCheck:
    default: 'false'
    description: Value of mount_check in Swift account/container/object -server.conf
    type: boolean
  NtpServer:
    default: ''
    type: string
  PartPower:
    default: 10
    description: Partition Power to use when building Swift rings
    type: number
  Replicas:
    default: 3
    description: How many replicas to use in the swift rings.
    type: number
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set via parameter_defaults
      in the resource registry.
    type: json
  SnmpdReadonlyUserName:
    default: ro_snmp_user
    description: The user name for SNMPd with readonly rights running on all Overcloud
      nodes
    type: string
  SnmpdReadonlyUserPassword:
    default: unset
    description: The user password for SNMPd with readonly rights running on all Overcloud
      nodes
    hidden: true
    type: string
  UpdateIdentifier:
    default: ''
    description: 'Setting to a previously unused value during stack-update will trigger
      package update on all nodes

      '
    type: string
resources:
  InternalApiPort:
    properties:
      ControlPlaneIP:
        get_attr:
        - SwiftStorage
        - networks
        - ctlplane
        - 0
    type: OS::TripleO::SwiftStorage::Ports::InternalApiPort
  NetIpMap:
    properties:
      InternalApiIp:
        get_attr:
        - InternalApiPort
        - ip_address
      StorageIp:
        get_attr:
        - StoragePort
        - ip_address
      StorageMgmtIp:
        get_attr:
        - StorageMgmtPort
        - ip_address
    type: OS::TripleO::Network::Ports::NetIpMap
  NetworkConfig:
    properties:
      InternalApiIpSubnet:
        get_attr:
        - InternalApiPort
        - ip_subnet
      StorageIpSubnet:
        get_attr:
        - StoragePort
        - ip_subnet
      StorageMgmtIpSubnet:
        get_attr:
        - StorageMgmtPort
        - ip_subnet
    type: OS::TripleO::ObjectStorage::Net::SoftwareConfig
  NetworkDeployment:
    properties:
      config:
        get_resource: NetworkConfig
      server:
        get_resource: SwiftStorage
    type: OS::TripleO::SoftwareDeployment
  NodeUserData:
    type: OS::TripleO::NodeUserData
  StorageMgmtPort:
    properties:
      ControlPlaneIP:
        get_attr:
        - SwiftStorage
        - networks
        - ctlplane
        - 0
    type: OS::TripleO::SwiftStorage::Ports::StorageMgmtPort
  StoragePort:
    properties:
      ControlPlaneIP:
        get_attr:
        - SwiftStorage
        - networks
        - ctlplane
        - 0
    type: OS::TripleO::SwiftStorage::Ports::StoragePort
  SwiftStorage:
    properties:
      flavor:
        get_param: Flavor
      image:
        get_param: Image
      key_name:
        get_param: KeyName
      name:
        get_param: Hostname
      networks:
      - network: ctlplane
      user_data:
        get_resource: NodeUserData
      user_data_format: SOFTWARE_CONFIG
    type: OS::Nova::Server
  SwiftStorageHieraConfig:
    properties:
      config:
        hiera:
          datafiles:
            common:
              raw_data:
                get_file: hieradata/common.yaml
            object:
              mapped_data:
                enable_package_install:
                  get_input: enable_package_install
                ntp::servers:
                  get_input: ntp_servers
                snmpd_readonly_user_name:
                  get_input: snmpd_readonly_user_name
                snmpd_readonly_user_password:
                  get_input: snmpd_readonly_user_password
                swift::storage::all::storage_local_net_ip:
                  get_input: swift_management_network
                swift::swift_hash_suffix:
                  get_input: swift_hash_suffix
                swift_mount_check:
                  get_input: swift_mount_check
                tripleo::ringbuilder::build_ring: true
                tripleo::ringbuilder::min_part_hours:
                  get_input: swift_min_part_hours
                tripleo::ringbuilder::part_power:
                  get_input: swift_part_power
                tripleo::ringbuilder::replicas:
                  get_input: swift_replicas
              raw_data:
                get_file: hieradata/object.yaml
          hierarchy:
          - heat_config_%{::deploy_config_name}
          - object
          - swift_devices_and_proxy
          - all_nodes
          - RedHat
          - common
      group: os-apply-config
    type: OS::Heat::StructuredConfig
  SwiftStorageHieraDeploy:
    depends_on: NetworkDeployment
    properties:
      config:
        get_resource: SwiftStorageHieraConfig
      input_values:
        enable_package_install:
          get_param: EnablePackageInstall
        local_ip:
          get_attr:
          - SwiftStorage
          - networks
          - ctlplane
          - 0
        ntp_servers:
          str_replace:
            params:
              server:
                get_param: NtpServer
            template: '["server"]'
        snmpd_readonly_user_name:
          get_param: SnmpdReadonlyUserName
        snmpd_readonly_user_password:
          get_param: SnmpdReadonlyUserPassword
        swift_hash_suffix:
          get_param: HashSuffix
        swift_management_network:
          get_attr:
          - NetIpMap
          - net_ip_map
          - get_param:
            - ServiceNetMap
            - SwiftMgmtNetwork
        swift_min_part_hours:
          get_param: MinPartHours
        swift_mount_check:
          get_param: MountCheck
        swift_part_power:
          get_param: PartPower
        swift_replicas:
          get_param: Replicas
      server:
        get_resource: SwiftStorage
    type: OS::Heat::StructuredDeployment
  UpdateConfig:
    type: OS::TripleO::Tasks::PackageUpdate
  UpdateDeployment:
    properties:
      config:
        get_resource: UpdateConfig
      input_values:
        update_identifier:
          get_param: UpdateIdentifier
      server:
        get_resource: SwiftStorage
    type: OS::Heat::SoftwareDeployment
